name: Branch Protection Check

# This workflow ensures all required checks pass before allowing merges to main
# It serves as a single required status check that depends on all CI jobs

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # This job waits for all CI checks and provides a single status check for branch protection
  all-checks-passed:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: 
      - check-ci-jobs
    steps:
      - name: All Required Checks Passed
        run: |
          echo "✅ All required CI checks have passed!"
          echo "This PR is ready to merge to main."

  # Job to verify all CI workflow jobs are passing
  check-ci-jobs:
    name: Verify CI Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Wait for CI workflow
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "CI"
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 3600 # 1 hour timeout
          intervalSeconds: 30
          
      - name: Check CI Results
        run: |
          if [ "${{ steps.wait-for-ci.outputs.conclusion }}" != "success" ]; then
            echo "❌ CI workflow did not complete successfully"
            echo "Status: ${{ steps.wait-for-ci.outputs.conclusion }}"
            exit 1
          else
            echo "✅ CI workflow completed successfully"
          fi